-- Update Prisma's Match table
ALTER TABLE "Match" 
ADD COLUMN IF NOT EXISTS "initiatedBy" TEXT,
ADD COLUMN IF NOT EXISTS "matchReasons" JSONB,
ADD COLUMN IF NOT EXISTS "acceptedAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "rejectedAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "closedAt" TIMESTAMP(3);

-- Update Sequelize's MATCHES table
ALTER TABLE "MATCHES" 
ADD COLUMN IF NOT EXISTS "initiated_by" TEXT,
ADD COLUMN IF NOT EXISTS "match_reasons" JSONB,
ADD COLUMN IF NOT EXISTS "accepted_at" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "rejected_at" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "closed_at" TIMESTAMP(3);

-- Update MatchStatus enum for Prisma
ALTER TYPE "MatchStatus" ADD VALUE IF NOT EXISTS 'RECHAZADO';
ALTER TYPE "MatchStatus" ADD VALUE IF NOT EXISTS 'CERRADO';
