-- 1. Actualizar EXALUMNOS
ALTER TABLE "EXALUMNOS" ADD COLUMN IF NOT EXISTS "biografia" TEXT;
ALTER TABLE "EXALUMNOS" ADD COLUMN IF NOT EXISTS "github_url" TEXT;
ALTER TABLE "EXALUMNOS" ADD COLUMN IF NOT EXISTS "website_url" TEXT;
ALTER TABLE "EXALUMNOS" ADD COLUMN IF NOT EXISTS "habilidades" JSONB;
ALTER TABLE "EXALUMNOS" ADD COLUMN IF NOT EXISTS "certificaciones" JSONB;
ALTER TABLE "EXALUMNOS" ADD COLUMN IF NOT EXISTS "experiencia_laboral" JSONB;
ALTER TABLE "EXALUMNOS" ADD COLUMN IF NOT EXISTS "ofrece_guest_speaking" BOOLEAN DEFAULT false;
ALTER TABLE "EXALUMNOS" ADD COLUMN IF NOT EXISTS "ofrece_volunteering" BOOLEAN DEFAULT false;
ALTER TABLE "EXALUMNOS" ADD COLUMN IF NOT EXISTS "ofrece_career_advice" BOOLEAN DEFAULT false;
ALTER TABLE "EXALUMNOS" ADD COLUMN IF NOT EXISTS "ofrece_networking" BOOLEAN DEFAULT false;

-- 2. Crear tabla CONNECTIONS
CREATE TABLE IF NOT EXISTS "CONNECTIONS" (
  "id" UUID PRIMARY KEY,
  "sender_id" UUID NOT NULL REFERENCES "USERS"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  "receiver_id" UUID NOT NULL REFERENCES "USERS"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  "status" TEXT NOT NULL DEFAULT 'pending',
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "unique_sender_receiver" UNIQUE ("sender_id", "receiver_id")
);

-- Índices para optimizar conexiones
CREATE INDEX IF NOT EXISTS "idx_connections_sender" ON "CONNECTIONS"("sender_id");
CREATE INDEX IF NOT EXISTS "idx_connections_receiver" ON "CONNECTIONS"("receiver_id");
CREATE INDEX IF NOT EXISTS "idx_connections_status" ON "CONNECTIONS"("status");

-- 3. Crear tabla NOTIFICATIONS
CREATE TABLE IF NOT EXISTS "NOTIFICATIONS" (
  "id" UUID PRIMARY KEY,
  "user_id" UUID NOT NULL REFERENCES "USERS"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  "title" TEXT NOT NULL,
  "message" TEXT NOT NULL,
  "type" TEXT NOT NULL,
  "read" BOOLEAN DEFAULT false,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Índices para optimizar notificaciones
CREATE INDEX IF NOT EXISTS "idx_notifications_user" ON "NOTIFICATIONS"("user_id");
CREATE INDEX IF NOT EXISTS "idx_notifications_read" ON "NOTIFICATIONS"("read");
